### ISSUE TITLE
Implement 'A Bold Proposition'

### ISSUE THREAD

**Issue by Siudhne** [Ernie0013/Intimate-Encounters#4]

**Comment by Ernie0013** [comment]
From what I saw you've been making translations for the tooltips why someone loses piety, but there should be a better way, because in other places you'll see something like this:
![image](https://user-images.githubusercontent.com/7670453/93511463-277e9480-f923-11ea-9394-0bfccbb9f485.png)
I think this is where `scripted_effects` would be beneficial.

**Comment by Ernie0013** [comment]
![image](https://user-images.githubusercontent.com/7670453/93615561-db3f5d00-f9d3-11ea-8f01-7d88e4664055.png)
